name: Fruits and Vegs PHP CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  phpcs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ 8.3 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, xml

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: Run PHPCS
        run: vendor/bin/phpcs

  phpstan:
    runs-on: ubuntu-latest
    needs: phpcs
    strategy:
      matrix:
        php: [ 8.3 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, xml

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse -c phpstan.dist.neon

  unit-tests:
    runs-on: ubuntu-latest
    needs: phpcs
    strategy:
      matrix:
        php: [ 8.3 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, xml

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: Run Unit Tests
        run: vendor/bin/phpunit --configuration phpunit.xml.dist --testsuite 'Project Test Suite'
